### PR TITLE
Build Enhancements + Nuget Publishing

### PR DESCRIPTION
**Pull request by wahmedswl**
Hi, this is initial pull request which will plug Paket + Cake for building and it also has Nuget publish support. Minor changes will be needed to fully automate publishing. Currently, we are using dll manually and we like to move to Nuget package as soon as its available #1

### CODE REVIEW

**Comment by SaxxonPike** [comment]
I see that the package has been uploaded to Nuget already. Is there a way to transfer ownership? There is a particular Nuget packaging process I like to use which is implemented in the `nuget` branch that doesn't require any additional tooling besides VS 2017.

**Comment by wahmedswl** [comment]
@SaxxonPike yeah, ownership can be transferred. Publishing to Nuget is nothing special just single call to Nuget api. I have used Paket + Cake as it help streamline the build process too much. I have windows only setup so i have used appveyor for ci. XBuild can also be done but i never used that with Cake.

If you really wanted to keep things simple, publishing to nuget can be extracted

**Comment by SaxxonPike** [comment]
I will handle the Appveyor deployment from here. Thanks for the suggestion! For now, please transfer ownership of the Nuget package to saxxonpike@gmail.com - I will make sure that further deployments to Nuget are automated.

**Comment by wahmedswl** [comment]
@SaxxonPike please provide nuget id for ownership

**Comment by SaxxonPike** [comment]
On Nuget:

ID: SaxxonPike
Email: saxxonpike@gmail.com

**Comment by wahmedswl** [comment]
Hi, added to owner after Approval, will remove me from owner and pkg will be officially yours

**Comment by SaxxonPike** [comment]
Thank you, looks like this worked!

**Comment by wahmedswl** [comment]
yeah, thats great :) when will be latest changes pushed?

**Comment by SaxxonPike** [comment]
This has been deployed to NuGet. I'm closing this issue as resolved.

https://www.nuget.org/packages/NextLevelSeven/1.0.0-master

**Pull request closed without merging**
